version: '3'
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      - TZ=Europe/Sofia
    volumes:
      - './etc-pihole:/etc-pihole'
      - './etc-dnsmasq.d:/etc-dnsmasq.d'
    restart: unless-stopped
